services:
  Server-minecraft:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      DIFFICULTY: normal
      SERVER_NAME: TurritosTurrones
      ONLINE_MODE: false
      JVM_OPTS: "-Xms2G -Xmx3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled"
    volumes:
      - ./data:/data
    networks:
      - minecraft-net
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
